### ISSUE TITLE
Map currently working features

### ISSUE THREAD

**Issue by LeandroSQ** [jpcurti/E3V3SE_display_klipper#30]
This serves both as a question and an enhancement request, 
What menus/features are currently supported? An what is still pending?

Also, thank you for you amazing work!

**Comment by jpcurti** [comment]
Hey Leandro.
I agree with you that such information should be visible on the project description so that someone decide that it even makes sense to try it out or not. I will update on the readme, thanks for your feedback.

FYI the basic function like pre-heating, homing, moving axis, printing parts, stoping and pausing print as well as monitoring print status, time left, current temps, are all working as expected. It may be that something value or text is not correct aligned or in the correct color, but the very minimum that someone would need to use the printer is there. I also think that some specific menus in the configuration section and the bed leveling menu would not bring much and therefore I would not focus on that, rather than focusing more on making a custom klipper to make the display communicate with the host via the display cable (through the MCU/ printer main board) instead of jumpers directly connected to the RPi. This would be the major update that would make this project finally useful for many people 😄 

I hope that this answers your question. Thanks again for your feedback and some motivation to work again on this, as I didn't notice that someone actually looked into it 😆 

Have a great week ahead.

Best regards,
Joao

**Comment by LeandroSQ** [comment]
Thanks for the quick reply!

You mentioned the axis manipulation is supported, does that extend to X, Y, Z and E? And if the Extruder is supported, would it be correct to assume that the `Retract` and `Extrude` buttons on the prepare menu are also operational? 
I ask since this would make a world of difference when switching different filaments.

I'm in the process of setting up Klipper and will do give this repo some testing once my SBC arrives. Unfortunately, delivery to my area is currently hindered by water, so I'm uncertain when it will arrive. Nevertheless, once I have the necessary hardware, I'm eager to contribute to this repository in any capacity, whether as a developer or tester, assuming you're willing to have me onboard

**Comment by jpcurti** [comment]
Added to main README with a GIF of the pop-up for non supported features:

The currently supported features are:

| Feature                | Status             |
|------------------------|--------------------|
| Print file             | :white_check_mark: |
| Tune print             | :white_check_mark: |
| Pause/continue print   | :white_check_mark: |
| Stop print             | :white_check_mark: |
| Move Axis              | :white_check_mark: |
| Home Axis              | :white_check_mark:
| Set Z offset           | :white_check_mark: |
| Disable step motors    | :white_check_mark: |
| Preheat bed            | :white_check_mark: |
| Cooldown               | :white_check_mark: |
| Set nozzle temperature | :white_check_mark: |
| Set bed temperature    | :white_check_mark: |
| Set max speed          | :x:                |
| Set max acceleration   | :x:                |
| Set steps per-mm       | :x:                |
| Leveling Menu          | :x:                |

**Comment by jpcurti** [comment]
To answer your other question: Yes, having someone actually using this too would be a good reason to continue this and I would gladly have your support in any way that you can. Some time ago I set a milestone (https://github.com/jpcurti/E3V3SE_display_klipper/milestone/2) to modify klipper so that we can create a communication between display and host (any, not only Rpi) through the mainboard, instead of jumpers connected directly to it. IMHO this would be an improvement that would make it plug and play and best suited for new users. Take a look on the open issues and the milestones and after you set it up on your printer, try to take one of the issues marked as "good first issue" as a start :)

Thanks for the interest in the project and I wish you a good week. 


PS: I am deeply sorry to hear about the floods in your region. My heart goes to the people who were affected by such an unfortunate event.
